[[constraint]]
  branch = "master"
  name = "github.com/gin-gonic/gin"

[[constraint]]
  branch = "master"
  name = "github.com/joho/godotenv"

[[constraint]]
  name = "github.com/json-iterator/go"
  version = "1.0.4"

[[constraint]]
  branch = "master"
  name = "github.com/pkg/errors"

[metadata.heroku]
  go-version = "go1.9.3"
  root-package = "github.com/y4htse/turtle-utils"
