[[constraint]]
  branch = "master"
  name = "github.com/gin-gonic/gin"

[[constraint]]
  branch = "master"
  name = "github.com/joho/godotenv"

[[constraint]]
  name = "github.com/json-iterator/go"
  version = "1.0.4"

[[constraint]]
  branch = "master"
  name = "github.com/pkg/errors"

[metadata]
heroku-go = "1.9.2"
heroku-install = "1.9.2"
heroku-root = "github.com/y4htse/turtle-utils"
